version: '3.3'

services:
    mysql:
        image: mysql:5.7.18
        container_name: bakerymysqldb
        environment: 
            MYSQL_ROOT_PASSWORD: "p4ssw0rd$$"
            MYSQL_DATABASE: "bakerydb"
        volumes: 
            - ./mysql-data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        networks: 
            - testnetwork

    bakeryapp:
        build: ./
        image: bakeryapp:latest
        container_name: runningBakeryApp
        restart: always
        ports: 
            - "8080:80"
        depends_on: 
            - mysql
        networks: 
            - testnetwork

volumes: 
    mysql-data:
networks: 
    testnetwork:
        driver: bridge